// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmI_eN1Xjz9wKhWZDiqfnZfuJ2usEFjv0',
    appId: '1:79374173660:web:1b8842ef3a8b7dc1a5bb19',
    messagingSenderId: '79374173660',
    projectId: 'rickandmark-e6e26',
    authDomain: 'rickandmark-e6e26.firebaseapp.com',
    storageBucket: 'rickandmark-e6e26.firebasestorage.app',
    measurementId: 'G-BZX2CEP4GS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDc90fRiazLGANt17l3utN5qBI4_BUBWM8',
    appId: '1:79374173660:android:0a4eca2f550a2883a5bb19',
    messagingSenderId: '79374173660',
    projectId: 'rickandmark-e6e26',
    storageBucket: 'rickandmark-e6e26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0qJUrjJDATUijUwqlt1VdXAqZkgZAL8s',
    appId: '1:79374173660:ios:2b34e4160f997c1da5bb19',
    messagingSenderId: '79374173660',
    projectId: 'rickandmark-e6e26',
    storageBucket: 'rickandmark-e6e26.firebasestorage.app',
    iosBundleId: 'com.example.rick',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0qJUrjJDATUijUwqlt1VdXAqZkgZAL8s',
    appId: '1:79374173660:ios:2b34e4160f997c1da5bb19',
    messagingSenderId: '79374173660',
    projectId: 'rickandmark-e6e26',
    storageBucket: 'rickandmark-e6e26.firebasestorage.app',
    iosBundleId: 'com.example.rick',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmI_eN1Xjz9wKhWZDiqfnZfuJ2usEFjv0',
    appId: '1:79374173660:web:c4e634f3d5aa1dcfa5bb19',
    messagingSenderId: '79374173660',
    projectId: 'rickandmark-e6e26',
    authDomain: 'rickandmark-e6e26.firebaseapp.com',
    storageBucket: 'rickandmark-e6e26.firebasestorage.app',
    measurementId: 'G-TJC48YG0K1',
  );
}
